version: 1
formatters:
  simple:
    format: '[%(levelname)s]  %(asctime)s  %(name)s  %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  console_err:
    class: logging.StreamHandler
    level: ERROR
    formatter: simple
    stream: ext://sys.stderr
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: log.txt
loggers:
  mylogger:
    level: DEBUG
    handlers: [file, console]
    propagate: no
  uvicorn.error:
    level: DEBUG
    handlers: [file, console_err]
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers: [file, console]
    propagate: no
  uvicorn.asgi:
    level: DEBUG
    handlers: [file, console]
    propagate: no
root:
  level: DEBUG
  handlers: [console_err]